site_name: MJ-NEXARA Docs
nav:
  - Home: index.md
  - About: about.md
  - Mission: mission.md
  - Employment:
      - Etherscan: Employment/etherscan.md
      - UNV: Employment/unv.md
theme:
  name: material

